bootnode:
bootnode-mode: true
data-dir: /home/bee/.bee-data
full-node: true
mainnet: false
network-id: 5
password: password
storage-incentives-enable: false
blockchain-rpc-endpoint: https://ethereum-sepolia-rpc.publicnode.com/ac5b7f52aabd778861c2588f872f15c5fc34f0b343ec3d18ac2e91f5526e9c2b
swap-enable: true
swap-initial-deposit: 0
verbosity: debug
welcome-message: "your welcome meessage"
warmup-time: 30s
block-time: "12"
p2p-addr: :1634
p2p-ws-enable: true
api-addr: :1633
